Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.network "private_network", ip: "192.168.35.10"
  config.vm.synced_folder "../www", "/var/www/kundenprojekt"
end
